/*
 * Production
 * Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EventListCancellationInsightEventsResponseEventsInnerSubscriptionsInner
 */
public class EventListCancellationInsightEventsResponseEventsInnerSubscriptionsInnerTest {
    private final EventListCancellationInsightEventsResponseEventsInnerSubscriptionsInner model = new EventListCancellationInsightEventsResponseEventsInnerSubscriptionsInner();

    /**
     * Model tests for EventListCancellationInsightEventsResponseEventsInnerSubscriptionsInner
     */
    @Test
    public void testEventListCancellationInsightEventsResponseEventsInnerSubscriptionsInner() {
        // TODO: test EventListCancellationInsightEventsResponseEventsInnerSubscriptionsInner
    }

    /**
     * Test the property 'oid'
     */
    @Test
    public void oidTest() {
        // TODO: test oid
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'canceledAt'
     */
    @Test
    public void canceledAtTest() {
        // TODO: test canceledAt
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'processed'
     */
    @Test
    public void processedTest() {
        // TODO: test processed
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'mrr'
     */
    @Test
    public void mrrTest() {
        // TODO: test mrr
    }

    /**
     * Test the property 'addOnMrr'
     */
    @Test
    public void addOnMrrTest() {
        // TODO: test addOnMrr
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

}
