/*
 * Production
 * Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MetricShowCohortsResponseInnerCellsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MetricShowCohortsResponseInner
 */
public class MetricShowCohortsResponseInnerTest {
    private final MetricShowCohortsResponseInner model = new MetricShowCohortsResponseInner();

    /**
     * Model tests for MetricShowCohortsResponseInner
     */
    @Test
    public void testMetricShowCohortsResponseInner() {
        // TODO: test MetricShowCohortsResponseInner
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'mrr'
     */
    @Test
    public void mrrTest() {
        // TODO: test mrr
    }

    /**
     * Test the property 'begin'
     */
    @Test
    public void beginTest() {
        // TODO: test begin
    }

    /**
     * Test the property 'cells'
     */
    @Test
    public void cellsTest() {
        // TODO: test cells
    }

    /**
     * Test the property 'customers'
     */
    @Test
    public void customersTest() {
        // TODO: test customers
    }

    /**
     * Test the property 'mrrFormatted'
     */
    @Test
    public void mrrFormattedTest() {
        // TODO: test mrrFormatted
    }

}
