/*
 * Production
 * Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MetricShowSummaryResponseMetricsInner
 */
public class MetricShowSummaryResponseMetricsInnerTest {
    private final MetricShowSummaryResponseMetricsInner model = new MetricShowSummaryResponseMetricsInner();

    /**
     * Model tests for MetricShowSummaryResponseMetricsInner
     */
    @Test
    public void testMetricShowSummaryResponseMetricsInner() {
        // TODO: test MetricShowSummaryResponseMetricsInner
    }

    /**
     * Test the property 'humanDate'
     */
    @Test
    public void humanDateTest() {
        // TODO: test humanDate
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'activeCustomers'
     */
    @Test
    public void activeCustomersTest() {
        // TODO: test activeCustomers
    }

    /**
     * Test the property 'activeSubscriptions'
     */
    @Test
    public void activeSubscriptionsTest() {
        // TODO: test activeSubscriptions
    }

    /**
     * Test the property 'addOnMrr'
     */
    @Test
    public void addOnMrrTest() {
        // TODO: test addOnMrr
    }

    /**
     * Test the property 'arpu'
     */
    @Test
    public void arpuTest() {
        // TODO: test arpu
    }

    /**
     * Test the property 'arr'
     */
    @Test
    public void arrTest() {
        // TODO: test arr
    }

    /**
     * Test the property 'cancellations'
     */
    @Test
    public void cancellationsTest() {
        // TODO: test cancellations
    }

    /**
     * Test the property 'coupons'
     */
    @Test
    public void couponsTest() {
        // TODO: test coupons
    }

    /**
     * Test the property 'downgrades'
     */
    @Test
    public void downgradesTest() {
        // TODO: test downgrades
    }

    /**
     * Test the property 'failedCharges'
     */
    @Test
    public void failedChargesTest() {
        // TODO: test failedCharges
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'ltv'
     */
    @Test
    public void ltvTest() {
        // TODO: test ltv
    }

    /**
     * Test the property 'mrr'
     */
    @Test
    public void mrrTest() {
        // TODO: test mrr
    }

    /**
     * Test the property 'netRevenue'
     */
    @Test
    public void netRevenueTest() {
        // TODO: test netRevenue
    }

    /**
     * Test the property 'newCustomers'
     */
    @Test
    public void newCustomersTest() {
        // TODO: test newCustomers
    }

    /**
     * Test the property 'otherRevenue'
     */
    @Test
    public void otherRevenueTest() {
        // TODO: test otherRevenue
    }

    /**
     * Test the property 'reactivatedCustomers'
     */
    @Test
    public void reactivatedCustomersTest() {
        // TODO: test reactivatedCustomers
    }

    /**
     * Test the property 'refunds'
     */
    @Test
    public void refundsTest() {
        // TODO: test refunds
    }

    /**
     * Test the property 'revenueChurn'
     */
    @Test
    public void revenueChurnTest() {
        // TODO: test revenueChurn
    }

    /**
     * Test the property 'trialConversions'
     */
    @Test
    public void trialConversionsTest() {
        // TODO: test trialConversions
    }

    /**
     * Test the property 'upgrades'
     */
    @Test
    public void upgradesTest() {
        // TODO: test upgrades
    }

    /**
     * Test the property 'userChurn'
     */
    @Test
    public void userChurnTest() {
        // TODO: test userChurn
    }

}
