/*
 * Production
 * Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SourceCreateSubscriptionRequestAddonsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SourceCreateSubscriptionRequest
 */
public class SourceCreateSubscriptionRequestTest {
    private final SourceCreateSubscriptionRequest model = new SourceCreateSubscriptionRequest();

    /**
     * Model tests for SourceCreateSubscriptionRequest
     */
    @Test
    public void testSourceCreateSubscriptionRequest() {
        // TODO: test SourceCreateSubscriptionRequest
    }

    /**
     * Test the property 'oid'
     */
    @Test
    public void oidTest() {
        // TODO: test oid
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'canceledAt'
     */
    @Test
    public void canceledAtTest() {
        // TODO: test canceledAt
    }

    /**
     * Test the property 'planOid'
     */
    @Test
    public void planOidTest() {
        // TODO: test planOid
    }

    /**
     * Test the property 'customerOid'
     */
    @Test
    public void customerOidTest() {
        // TODO: test customerOid
    }

    /**
     * Test the property 'addons'
     */
    @Test
    public void addonsTest() {
        // TODO: test addons
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

}
