/*
 * Production
 * Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SourceCreatePlanResponsePlanAmountsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SourceCreatePlanResponsePlan
 */
public class SourceCreatePlanResponsePlanTest {
    private final SourceCreatePlanResponsePlan model = new SourceCreatePlanResponsePlan();

    /**
     * Model tests for SourceCreatePlanResponsePlan
     */
    @Test
    public void testSourceCreatePlanResponsePlan() {
        // TODO: test SourceCreatePlanResponsePlan
    }

    /**
     * Test the property 'oid'
     */
    @Test
    public void oidTest() {
        // TODO: test oid
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'intervalCount'
     */
    @Test
    public void intervalCountTest() {
        // TODO: test intervalCount
    }

    /**
     * Test the property 'trialDuration'
     */
    @Test
    public void trialDurationTest() {
        // TODO: test trialDuration
    }

    /**
     * Test the property 'trialDurationUnit'
     */
    @Test
    public void trialDurationUnitTest() {
        // TODO: test trialDurationUnit
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'setupFees'
     */
    @Test
    public void setupFeesTest() {
        // TODO: test setupFees
    }

    /**
     * Test the property 'amounts'
     */
    @Test
    public void amountsTest() {
        // TODO: test amounts
    }

}
