/*
 * Production
 * Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SegmentGetFieldsResponseBaremetricsInner;
import com.konfigthis.client.model.SegmentGetFieldsResponseClearbitInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SegmentGetFieldsResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SegmentGetFieldsResponse {
  public static final String SERIALIZED_NAME_BAREMETRICS = "baremetrics";
  @SerializedName(SERIALIZED_NAME_BAREMETRICS)
  private List<SegmentGetFieldsResponseBaremetricsInner> baremetrics = null;

  public static final String SERIALIZED_NAME_CLEARBIT = "clearbit";
  @SerializedName(SERIALIZED_NAME_CLEARBIT)
  private List<SegmentGetFieldsResponseClearbitInner> clearbit = null;

  public SegmentGetFieldsResponse() {
  }

  public SegmentGetFieldsResponse baremetrics(List<SegmentGetFieldsResponseBaremetricsInner> baremetrics) {
    
    
    
    
    this.baremetrics = baremetrics;
    return this;
  }

  public SegmentGetFieldsResponse addBaremetricsItem(SegmentGetFieldsResponseBaremetricsInner baremetricsItem) {
    if (this.baremetrics == null) {
      this.baremetrics = new ArrayList<>();
    }
    this.baremetrics.add(baremetricsItem);
    return this;
  }

   /**
   * Get baremetrics
   * @return baremetrics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SegmentGetFieldsResponseBaremetricsInner> getBaremetrics() {
    return baremetrics;
  }


  public void setBaremetrics(List<SegmentGetFieldsResponseBaremetricsInner> baremetrics) {
    
    
    
    this.baremetrics = baremetrics;
  }


  public SegmentGetFieldsResponse clearbit(List<SegmentGetFieldsResponseClearbitInner> clearbit) {
    
    
    
    
    this.clearbit = clearbit;
    return this;
  }

  public SegmentGetFieldsResponse addClearbitItem(SegmentGetFieldsResponseClearbitInner clearbitItem) {
    if (this.clearbit == null) {
      this.clearbit = new ArrayList<>();
    }
    this.clearbit.add(clearbitItem);
    return this;
  }

   /**
   * Get clearbit
   * @return clearbit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SegmentGetFieldsResponseClearbitInner> getClearbit() {
    return clearbit;
  }


  public void setClearbit(List<SegmentGetFieldsResponseClearbitInner> clearbit) {
    
    
    
    this.clearbit = clearbit;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SegmentGetFieldsResponse instance itself
   */
  public SegmentGetFieldsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentGetFieldsResponse segmentGetFieldsResponse = (SegmentGetFieldsResponse) o;
    return Objects.equals(this.baremetrics, segmentGetFieldsResponse.baremetrics) &&
        Objects.equals(this.clearbit, segmentGetFieldsResponse.clearbit)&&
        Objects.equals(this.additionalProperties, segmentGetFieldsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baremetrics, clearbit, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentGetFieldsResponse {\n");
    sb.append("    baremetrics: ").append(toIndentedString(baremetrics)).append("\n");
    sb.append("    clearbit: ").append(toIndentedString(clearbit)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("baremetrics");
    openapiFields.add("clearbit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SegmentGetFieldsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SegmentGetFieldsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SegmentGetFieldsResponse is not found in the empty JSON string", SegmentGetFieldsResponse.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("baremetrics") != null && !jsonObj.get("baremetrics").isJsonNull()) {
        JsonArray jsonArraybaremetrics = jsonObj.getAsJsonArray("baremetrics");
        if (jsonArraybaremetrics != null) {
          // ensure the json data is an array
          if (!jsonObj.get("baremetrics").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `baremetrics` to be an array in the JSON string but got `%s`", jsonObj.get("baremetrics").toString()));
          }

          // validate the optional field `baremetrics` (array)
          for (int i = 0; i < jsonArraybaremetrics.size(); i++) {
            SegmentGetFieldsResponseBaremetricsInner.validateJsonObject(jsonArraybaremetrics.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("clearbit") != null && !jsonObj.get("clearbit").isJsonNull()) {
        JsonArray jsonArrayclearbit = jsonObj.getAsJsonArray("clearbit");
        if (jsonArrayclearbit != null) {
          // ensure the json data is an array
          if (!jsonObj.get("clearbit").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `clearbit` to be an array in the JSON string but got `%s`", jsonObj.get("clearbit").toString()));
          }

          // validate the optional field `clearbit` (array)
          for (int i = 0; i < jsonArrayclearbit.size(); i++) {
            SegmentGetFieldsResponseClearbitInner.validateJsonObject(jsonArrayclearbit.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SegmentGetFieldsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SegmentGetFieldsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SegmentGetFieldsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SegmentGetFieldsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SegmentGetFieldsResponse>() {
           @Override
           public void write(JsonWriter out, SegmentGetFieldsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SegmentGetFieldsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SegmentGetFieldsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SegmentGetFieldsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SegmentGetFieldsResponse
  * @throws IOException if the JSON string is invalid with respect to SegmentGetFieldsResponse
  */
  public static SegmentGetFieldsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SegmentGetFieldsResponse.class);
  }

 /**
  * Convert an instance of SegmentGetFieldsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

